== Project Loom - Code samples

Code examples are divided by package name and Project Loom Early-Access builds can be downloaded from http://jdk.java.net/loom/

=== hello

Check the ways how to create Virtual Threads and Virtual Thread Pool

=== crash

See how JVM crash if we try to create 1_000_000 threads, and how Virtual Threads handle

=== sync_async

See how synchronous and asynchronous code look. Asynchronous scale but has disadvantages. Structured concurrency scales and don't have disadvantages in Asynchronous APIs.

=== pool

See how Virtual Thread Pools are scalable in terms of blocking operations.

=== perf

See how Virtual Threads are efficient when using blocking operations.

=== props

Hints the parallelism configuration for the Virtual Thread Pool.

=== Slides

link:https://github.com/rahmanusta/project-loom-samples/blob/master/slides/Project%20Loom%20-%20Scalable%20Concurrency%20with%20Virtual%20Java%20Threads.pdf[Project Loom - Scalable Concurrency with Virtual Java Threads]

=== Author
Rahman Usta
https://github.com/rahmanusta

=== License

MIT


